export const undergraduate = [
  {
    name: "B.A (Hindi)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (English)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Sanskrit)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Political Science)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (History)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Sociology)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Public Administration)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Economics)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Education)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Social Work)",
    eligibility: "10+2 or Its Equivalent",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.A (Journalism & Mass Communication)",
    eligibility: "10+2",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "Bachelor of Commerce (B.Com)",
    eligibility: "10+2",
    duration: 3,
    mode: "Yearly",
  },
  { name: "BBA", eligibility: "10+2", duration: 3, mode: "Yearly" },
  {
    name: "B.Sc (General)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Mathematics)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Physics)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Chemistry)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Botany)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Zoology)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Microbiology)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Bio-Chemistry)",
    eligibility: "10+2 With Science",
    duration: 3,
    mode: "Yearly",
  },
  { name: "BCA", eligibility: "10+2", duration: 3, mode: "Yearly" },
  {
    name: "B.Sc Information Technology (IT)",
    eligibility: "10+2",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Biotechnology)",
    eligibility: "10+2",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "B.Sc (Hotel Administration & Hospitality)",
    eligibility: "10+2",
    duration: 3,
    mode: "Yearly",
  },
  {
    name: "Bachelor of Library Information Science (B.L.I.S)",
    eligibility: "Graduation",
    duration: 1,
    mode: "Yearly",
  },
];

export const postgraduate = [
  {
    name: "Master of Commerce (M.Com)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Human Rights)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Hindi)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (English)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Political Science)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (History)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Sociology)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Education)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Public Administration)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A (Journalism & Mass Communication)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "Master of Social Work (M.S.W)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "Master of Library Information Science (M.L.I.S)",
    eligibility: "B.L.I.S",
    duration: 1,
    mode: "Yearly",
  },
  { name: "MBA", eligibility: "Graduation", duration: 2, mode: "Yearly" },
  { name: "MCA", eligibility: "Graduation", duration: 3, mode: "Yearly" },
  {
    name: "M.Sc Computer Science",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc Information Technology (IT)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Mathematics)",
    eligibility: "B.Sc With Relevant Subject",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Chemistry)",
    eligibility: "B.Sc With Relevant Subject",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Physics)",
    eligibility: "B.Sc With Relevant Subject",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Environment Science)",
    eligibility: "B.Sc With PCM/PCB",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Biotechnology)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.Sc (Bioinformatics)",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
  {
    name: "M.A in Yoga and Health Education",
    eligibility: "Graduation",
    duration: 2,
    mode: "Yearly",
  },
];

export const diploma = [
  {
    name: "Diploma in Business Management",
    eligibility: "10+2",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Diploma in Hospital Management",
    eligibility: "10+2",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Diploma in Retail Management",
    eligibility: "10+2",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Diploma in Hotel Management",
    eligibility: "10+2",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Diploma in Hospitality Management",
    eligibility: "10+2",
    duration: 1,
    mode: "Yearly",
  },
];

export const diplomaEngineering = [
  {
    name: "Diploma Engineering (Civil & Architecture)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Mechanical Engineering)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Electrical & Electronics)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Information Technology)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Computer Science Engineering)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Automobile Engineering)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
  {
    name: "Diploma Engineering (Electronics & Telecommunication Engineering)",
    eligibility: "10TH",
    duration: 3,
    mode: "Semester",
  },
];

export const postgraduateDiploma = [
  {
    name: "Post Graduate Diploma in Hotel Management and Tourism",
    eligibility: "Graduation",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Post Graduate Diploma in Business Management",
    eligibility: "Graduation",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Post Graduate Diploma in International Business",
    eligibility: "Graduation",
    duration: 1,
    mode: "Yearly",
  },
  {
    name: "Post Graduate Diploma in Computer Application (PGDCA)",
    eligibility: "Graduation",
    duration: 1,
    mode: "Yearly",
  },
];
export const btech = [
  {
    courseName: "BE (Mechanical Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Computer Science and Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Mechatronics)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Computer Science & Software Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Electronics & Communication Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Electrical & Electronics Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Civil Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Petroleum Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Automobile Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE (Aeronautical Engineering)",
    eligibility: "12th",
    duration: 4,
    mode: "Semester",
  },
  {
    courseName: "BE - B TECH LATERAL ENTRY",
    eligibility: "Diploma In 3 year",
    duration: 3,
    mode: "Semester",
  },
];

export const mtech = [
  {
    courseName: "ME (Mechanical Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Computer Science and Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Electronics & Instrumentation Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Electronics & Communication Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Electrical & Electronics Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Civil Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Automobile Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Information Technology)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Structural Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
  {
    courseName: "ME (Applied Engineering)",
    eligibility: "BE & BTECH With Relevant subject",
    duration: 2,
    mode: "Semester",
  },
];

export const univCourses = [
  { courseName: "BA", eligibility: "12th Pass", duration: 3, mode: "Semester" },
  { courseName: "BA-JMC", eligibility: "12th Pass", duration: 3, mode: "Semester" },
  { courseName: "BBA", eligibility: "12th Pass", duration: 3, mode: "Semester" },
  { courseName: "BBA-HCLTECH-DATA_ANALYTICS", eligibility: "12th Pass with Math", duration: 3, mode: "Semester" },
  { courseName: "BCA", eligibility: "12th Pass with Math/CS", duration: 3, mode: "Semester" },
  { courseName: "BCA-TCSION_DATAANALYTICS", eligibility: "12th Pass with Math", duration: 3, mode: "Semester" },
  { courseName: "BCA-TCSION_CLOUDSECURITY", eligibility: "12th Pass with CS/IT", duration: 3, mode: "Semester" },
  { courseName: "BCA-HCLTECH-DATA_ENGINEERING", eligibility: "12th Pass with Math", duration: 3, mode: "Semester" },
  { courseName: "BCA-HCLTECH-SOFTWARE_ENGINEERING", eligibility: "12th Pass with CS", duration: 3, mode: "Semester" },
  { courseName: "BCOM", eligibility: "12th Pass (Commerce Preferred)", duration: 3, mode: "Semester" },
  { courseName: "BCOM-ACCA", eligibility: "12th Pass (Commerce)", duration: 3, mode: "Semester" },
  { courseName: "BSC-HON-IT", eligibility: "12th Pass with Math/Science", duration: 3, mode: "Semester" },
  { courseName: "MA-JMC", eligibility: "Graduation in any discipline", duration: 2, mode: "Semester" },
  { courseName: "MA-PPG", eligibility: "Graduation in Political Science/Public Admin", duration: 2, mode: "Semester" },
  { courseName: "MBA", eligibility: "Any UG Degree", duration: 2, mode: "Semester" },
  { courseName: "MBA DUAL SPECIALIZATION", eligibility: "Any UG Degree", duration: 2, mode: "Semester" },
  { courseName: "MBA-ACCA", eligibility: "B.Com/BBA or related", duration: 2, mode: "Semester" },
  { courseName: "MBA GENERAL MANAGEMENT", eligibility: "Any UG Degree", duration: 2, mode: "Semester" },
  { courseName: "MCA", eligibility: "BCA/BSc CS/IT", duration: 2, mode: "Semester" },
  { courseName: "MCA-TCSION-ML", eligibility: "BCA/BSc CS", duration: 2, mode: "Semester" },
  { courseName: "MCA-TCSION-ARVR", eligibility: "BCA/BSc with Math", duration: 2, mode: "Semester" },
  { courseName: "MCA-HCLTECH-SOFTWARE_ENGINEERING", eligibility: "BCA/BSc CS", duration: 2, mode: "Semester" },
  { courseName: "MCA-HCLTECH-CYBERSECURITY", eligibility: "BCA/BSc CS", duration: 2, mode: "Semester" },
  { courseName: "MCOM-FM", eligibility: "BCom/BBA", duration: 2, mode: "Semester" },
  { courseName: "MSC-EVS", eligibility: "BSc in Environmental Science or equivalent", duration: 2, mode: "Semester" },
  { courseName: "MSC-IT", eligibility: "BSc IT/CS or equivalent", duration: 2, mode: "Semester" },
  { courseName: "BCOM-HONS", eligibility: "12th Pass (Commerce)", duration: 3, mode: "Semester" },
  { courseName: "MA-PSYCHOLOGY", eligibility: "BA Psychology or equivalent", duration: 2, mode: "Semester" },
  { courseName: "MSC-DATA SCIENCE", eligibility: "BSc/BE/BCA with Math", duration: 2, mode: "Semester" },
  { courseName: "BBA+MBA", eligibility: "12th Pass", duration: 5, mode: "Semester" },
  { courseName: "BCOM+MBA", eligibility: "12th Pass", duration: 5, mode: "Semester" },
  { courseName: "BCA+MCA", eligibility: "12th Pass with Math/CS", duration: 5, mode: "Semester" },
];
